[project]
name = "amarillo-enhancer"
version = "2.0.2"
description = "FastAPI app to enhance carpool offers from Amarillo"
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
    "amarillo>=2.0.1",
    "amarillo-stops",
    "shapely==2.0.2",
]
[tool.setuptools.packages]
find = {}
